### PR TITLE
fix(chatreactiontype): proper interface unmarshalling

### PR DESCRIPTION
**Pull request by heffcodex**
Hi. There is another bug showed up after #47 fix.
The fact is that `ChatReactionType` couldn't be unmarshalled from JSON as it is an interface. So all api responses that use this field type would fail to decode.
I came up with this workaround with minimal changes to the existing design. IDK if it is acceptable, but I'd share this anyway ;)

### CODE REVIEW

**Comment by NicoNex** [comment]
Thank you for the bug report, I think it would be best to make `ReactionType` implement the interface `json.Unmarshaler` by composition and thus implementing the required method `UnmarshalJSON([]byte) error`.
https://pkg.go.dev/encoding/json#Unmarshaler

```go
type ReactionType interface {
    ImplementsReactionType()
    json.Unmarshaler
}
```

**Comment by heffcodex** [comment]
But it would still require using a wrapper struct for the `ReactionType` interface as interfaces in Go can't be decoded directly: https://go.dev/play/p/Cbnkzfho1dw

As an alternative, we could replace the `ReactionType` interface in responses by an all-in-one struct containing either all possible fields:
```
type ReactionType struct {
  Type string `json:"type"`
  Emoji string `json:"emoji"`
  CustomEmoji string `json:"custom_emoji"`
}
```

Or embed all possible subtypes in it:
```
type ReactionType struct {
  Type string `json:"type"`
  *ReactionTypeEmoji
  *ReactionTypeCustomEmoji
}
```

Obviously it could be also done with reflection, but I believe that is not the case where it is wanted.

**Comment by NicoNex** [comment]
Sorry for the late response, you're right we can't use the interface in the way I suggested, I think at this point the best way is the embedding you suggested:

```go
type ReactionType struct {
  Type string `json:"type"`
  Emoji string `json:"emoji"`
  CustomEmoji string `json:"custom_emoji"`
}
```

**Comment by heffcodex** [comment]
@NicoNex I see that you have implemented the fix, could we close this PR then? And thank you :)

**Comment by NicoNex** [comment]
> @NicoNex I see that you have implemented the fix, could we close this PR then? And thank you :)

Thank you for the bug report and PR, sure this can be closed. :)

**Pull request closed without merging**
